FROM python:3.11 as build

COPY requirements.txt /tmp/requirements.txt
RUN python3 -m venv /dock_env
RUN /dock_env/bin/pip install -r /tmp/requirements.txt


FROM python:3.11
COPY --from=build /dock_env /dock_env
VOLUME [ "/app" ]
WORKDIR "/app"
EXPOSE 80
CMD [ "bash", "/app/docker_def/entrypoint.bash" ]
